# Main Terraform configuration for Azure Container Apps
# Generated by Terraform Repo Manager

terraform {
  required_version = ">=1.5"
  
  required_providers {
    azure = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

resource "azurerm_resource_group" "main" {
  name     = "rg-main-${var.environment}"
  location = "var.location"
  
  tags = var.default_tags
}
resource "azurerm_log_analytics_workspace" "main" {
  # Configure log_analytics_workspace here
  resource_group_name = azurerm_resource_group.main.name
  location           = azurerm_resource_group.main.location
  
  tags = var.default_tags
}
resource "azurerm_container_app_environment" "main" {
  # Configure container_app_environment here
  resource_group_name = azurerm_resource_group.main.name
  location           = azurerm_resource_group.main.location
  
  tags = var.default_tags
}
resource "azurerm_container_app" "main" {
  # Configure container_app here
  resource_group_name = azurerm_resource_group.main.name
  location           = azurerm_resource_group.main.location
  
  tags = var.default_tags
}
resource "azurerm_storage_account" "main" {
  name                     = "stmain${random_id.storage_suffix.hex}"
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  
  tags = var.default_tags
}
